### ISSUE TITLE
Create monadic EvaluationResult to replace Option

### ISSUE THREAD

**Issue by jhkuperus** [scala-rules/scala-rules#54]
For proper error handling, we are going to need an extension over the `Option` type. Preferably, we'd have something like this:

``` scala
sealed trait EvaluationResult[+A]

case class Some[+A](val value: A) extends EvaluationResult[A]
case class None[+A] extends EvaluationResult[A]
case class Error[+A](val exception: Exception) extends EvaluationResult[A]
```

This will allow us to differentiate between the cases in which a value simply was not available and when an exception occurred preventing the proper completion of an evaluation.

**Comment by NRBPerdijk** [comment]
I think we can achieve the desired behaviour by wrapping the option in a Try or Future.

**Comment by NRBPerdijk** [comment]
I think we can get the same result bij using Success and Failure

**Comment by jhkuperus** [comment]
:) Way to rein me in there trying to create something that's basically expressed as easily as this:

``` scala
type EvaluationResult[A] = Try[Option[A]]
```

I'll have to think about the `Future` you mention, it may actually open the door to allowing evaluations which are considered to be asynchronous.

**Comment by NRBPerdijk** [comment]
Sometimes the wheel has already been invented! ^^
