### ISSUE TITLE
Create afgerond op aantal decimalen DSL for Bedrag

### ISSUE THREAD

**Issue by NRBPerdijk** [scala-rules/scala-rules#58]
Create functionality that lets users round percentages as such:

Gegeven(condition) Bereken
 afgerondBedrag is (origineelBedrag naarBeneden afgerond op 3 decimalen)

With alternatives for "naarBeneden" and any Integer for 3.

**Comment by jhkuperus** [comment]
This issue basically duplicates #48?

**Comment by NRBPerdijk** [comment]
yes, but this time for amounts rather than percentages.

**Comment by jhkuperus** [comment]
Found a tiny bug still in the way the words were integrated into the DSL. Patched that in new PR.
